/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.co.technocrafts;

import epson.plq20.ScanParam;
import java.awt.Color;
import java.util.ArrayList;
import java.util.function.Consumer;

/**
 *
 * @author prashant
 */
public class EpsonFrame extends javax.swing.JFrame {

    /**
     * Creates new form EpsonFrame
     */
    EpsonPLQ22 objEpsonPLQ22 = new EpsonPLQ22();
    ScanParam objScanParam = new ScanParam();

    public EpsonFrame() {
        initComponents();
        ArrayList<Integer> numbers = new ArrayList<Integer>();
        numbers.add(5);
        numbers.add(9);
        numbers.add(8);
        numbers.add(1);
        Consumer<Integer> method = (n) -> {
            System.out.println(n);
        };
        numbers.forEach(method);
        objEpsonPLQ22 = new EpsonPLQ22();
        objScanParam = new ScanParam();

        String result = System.getProperty("os.arch");

        if (result.contains("64")) {
        } else {
            btnPrintImage.setVisible(false);
            txtNoOfLines.setVisible(false);
            lblNoOfLines.setVisible(false);
        }
        
        lblVersion.setText(objEpsonPLQ22.strversion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        btnPrinterStatus = new javax.swing.JButton();
        btnPaperLoad = new javax.swing.JButton();
        btnPaperEject = new javax.swing.JButton();
        btnScanBarcode = new javax.swing.JButton();
        btnScanPassbook = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnPrintImage = new javax.swing.JButton();
        btnPaperStatus = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        lblNoOfLines = new javax.swing.JLabel();
        txtNoOfLines = new javax.swing.JTextField();
        lblVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLQ22");

        lblStatus.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnPrinterStatus.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPrinterStatus.setText("Printer Status");
        btnPrinterStatus.setPreferredSize(new java.awt.Dimension(80, 40));
        btnPrinterStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrinterStatusActionPerformed(evt);
            }
        });

        btnPaperLoad.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPaperLoad.setText("Paper Load");
        btnPaperLoad.setPreferredSize(new java.awt.Dimension(80, 40));
        btnPaperLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperLoadActionPerformed(evt);
            }
        });

        btnPaperEject.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPaperEject.setText("Paper Eject");
        btnPaperEject.setPreferredSize(new java.awt.Dimension(80, 40));
        btnPaperEject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperEjectActionPerformed(evt);
            }
        });

        btnScanBarcode.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnScanBarcode.setText("Scan Barcode");
        btnScanBarcode.setPreferredSize(new java.awt.Dimension(80, 40));
        btnScanBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanBarcodeActionPerformed(evt);
            }
        });

        btnScanPassbook.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnScanPassbook.setText("Scan Passbook");
        btnScanPassbook.setPreferredSize(new java.awt.Dimension(80, 40));
        btnScanPassbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanPassbookActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(80, 40));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnPrintImage.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPrintImage.setText("Print Image");
        btnPrintImage.setPreferredSize(new java.awt.Dimension(80, 40));
        btnPrintImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintImageActionPerformed(evt);
            }
        });

        btnPaperStatus.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPaperStatus.setText("Paper Status");
        btnPaperStatus.setPreferredSize(new java.awt.Dimension(80, 40));
        btnPaperStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperStatusActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setPreferredSize(new java.awt.Dimension(80, 40));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        lblNoOfLines.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNoOfLines.setText("Number of lines :");
        lblNoOfLines.setPreferredSize(new java.awt.Dimension(80, 40));

        txtNoOfLines.setPreferredSize(new java.awt.Dimension(80, 40));
        txtNoOfLines.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoOfLinesKeyTyped(evt);
            }
        });

        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("version");
        lblVersion.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnScanBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnScanPassbook, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPaperLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPaperEject, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrinterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPaperStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrintImage, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(lblNoOfLines, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtNoOfLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrinterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaperStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaperLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaperEject, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnScanBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnScanPassbook, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrintImage, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoOfLines, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoOfLines, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblVersion)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrinterStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrinterStatusActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strClickStatus = objEpsonPLQ22.devStatusEpson();
        lblStatus.setText(strClickStatus);


    }//GEN-LAST:event_btnPrinterStatusActionPerformed

    private void btnPaperStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperStatusActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strClickStatus = objEpsonPLQ22.papStatusEpson();
        lblStatus.setText(strClickStatus);


    }//GEN-LAST:event_btnPaperStatusActionPerformed

    private void btnPaperLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperLoadActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strClickStatus = objEpsonPLQ22.prtLoadEpson();
        lblStatus.setText(strClickStatus);


    }//GEN-LAST:event_btnPaperLoadActionPerformed

    private void btnPaperEjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperEjectActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strClickStatus = objEpsonPLQ22.ejectEpson();
        lblStatus.setText(strClickStatus);


    }//GEN-LAST:event_btnPaperEjectActionPerformed

    private void btnScanBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanBarcodeActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strClickStatus = objEpsonPLQ22.scanBarcodeEpson();
        lblStatus.setText(strClickStatus);


    }//GEN-LAST:event_btnScanBarcodeActionPerformed

    private void btnScanPassbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanPassbookActionPerformed
        // TODO add your handling code here:
        String[] strScanPassbookStatus;
        final String strinparam = "";

        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strScanPassbookStatus = objEpsonPLQ22.scanPBEpson(strinparam);

        if (objEpsonPLQ22.intcount == 0) {
            lblStatus.setText(strScanPassbookStatus[0] + "," + strScanPassbookStatus[1]);
        } else {
            lblStatus.setText(strScanPassbookStatus[0] + strScanPassbookStatus[1]);
            objEpsonPLQ22.intcount = 0;
        }


    }//GEN-LAST:event_btnScanPassbookActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strClickStatus = objEpsonPLQ22.printPBEpson();
        lblStatus.setText(strClickStatus);


    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);
        strClickStatus = objEpsonPLQ22.resetDeviceEpson();
        lblStatus.setText(strClickStatus);


    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintImageActionPerformed
        // TODO add your handling code here:
        String strClickStatus = new String("");
        lblStatus.setText(strClickStatus);

        try {
            lblNoOfLines.setForeground(Color.BLACK);

            lblStatus.setText("");
            String printImageStatus = "";
            String imageLines = txtNoOfLines.getText();
            if (imageLines.length() == 0) {
                lblNoOfLines.setForeground(Color.red);
            } else {
//
//            JFileChooser openFile = new JFileChooser();
//            openFile.showOpenDialog(null);
//            File selectedFile = openFile.getSelectedFile();
//            String path = selectedFile.getAbsolutePath();
                //       linux.checkAutoStart();
                int no = Integer.parseInt(txtNoOfLines.getText());
                printImageStatus = objEpsonPLQ22.PrintImageEpson(no);
//            Tracer_Class.WriteToTransactionLogs(linux.logPath, "printPBStatus---> " + printPBStatus);
                lblStatus.setText(printImageStatus);
            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_btnPrintImageActionPerformed

    private void txtNoOfLinesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfLinesKeyTyped
        // TODO add your handling code here:
        lblNoOfLines.setForeground(Color.BLACK);

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || c == evt.VK_BACK_SPACE || c == evt.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNoOfLinesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EpsonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EpsonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EpsonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EpsonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EpsonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaperEject;
    private javax.swing.JButton btnPaperLoad;
    private javax.swing.JButton btnPaperStatus;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnPrintImage;
    private javax.swing.JButton btnPrinterStatus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnScanBarcode;
    private javax.swing.JButton btnScanPassbook;
    private javax.swing.JLabel lblNoOfLines;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JTextField txtNoOfLines;
    // End of variables declaration//GEN-END:variables
}
