/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartplugts;

import in.co.technocrafts.SmartPlugDeviceTS;

/**
 *
 * @author prashant
 */
public class SmartPlugTest extends javax.swing.JFrame {

    /**
     * Creates new form SmartPlugTest
     */
    SmartPlugDeviceTS objSmartPlug_Grayhats;

    public SmartPlugTest() {
        initComponents();
        this.objSmartPlug_Grayhats = new SmartPlugDeviceTS();

        lblSmartPlugVersion.setText(objSmartPlug_Grayhats.version);
        System.out.println(objSmartPlug_Grayhats.version);
      //  objSmartPlug_Grayhats.reset12SmartPlug();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSmartPlugStatus = new javax.swing.JLabel();
        btnSmartPlugOff = new javax.swing.JButton();
        btnSmartPlugStatus = new javax.swing.JButton();
        btnSmartPlugReset = new javax.swing.JButton();
        btnSmartPlugOn = new javax.swing.JButton();
        lblSmartPlugVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Plug");

        lblSmartPlugStatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblSmartPlugStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnSmartPlugOff.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSmartPlugOff.setText("Off");
        btnSmartPlugOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartPlugOffActionPerformed(evt);
            }
        });

        btnSmartPlugStatus.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSmartPlugStatus.setText("Status");
        btnSmartPlugStatus.setMinimumSize(new java.awt.Dimension(61, 20));
        btnSmartPlugStatus.setPreferredSize(new java.awt.Dimension(61, 20));
        btnSmartPlugStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartPlugStatusActionPerformed(evt);
            }
        });

        btnSmartPlugReset.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSmartPlugReset.setText("Reset");
        btnSmartPlugReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartPlugResetActionPerformed(evt);
            }
        });

        btnSmartPlugOn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSmartPlugOn.setText("On");
        btnSmartPlugOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartPlugOnActionPerformed(evt);
            }
        });

        lblSmartPlugVersion.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblSmartPlugVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSmartPlugStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnSmartPlugStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSmartPlugReset, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblSmartPlugVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSmartPlugOn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnSmartPlugOff, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblSmartPlugStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSmartPlugOff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmartPlugStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmartPlugOn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSmartPlugVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSmartPlugReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSmartPlugStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartPlugStatusActionPerformed
        // TODO add your handling code here:
        this.lblSmartPlugStatus.setText("");
        final String[] strvalue = this.objSmartPlug_Grayhats.statusSmartPlug();
        if (strvalue[0].equalsIgnoreCase(strvalue[1])) {
            this.lblSmartPlugStatus.setText(strvalue[0]);
        } else {
            this.lblSmartPlugStatus.setText("Status:" + strvalue[0] + "  Version:" + strvalue[1] + " ID:" + strvalue[2]);
        }
    }//GEN-LAST:event_btnSmartPlugStatusActionPerformed

    private void btnSmartPlugOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartPlugOnActionPerformed
        // TODO add your handling code here:
        this.lblSmartPlugStatus.setText("");
        this.lblSmartPlugStatus.setText(this.objSmartPlug_Grayhats.onSmartPlug());

    }//GEN-LAST:event_btnSmartPlugOnActionPerformed

    private void btnSmartPlugOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartPlugOffActionPerformed
        // TODO add your handling code here:
        this.lblSmartPlugStatus.setText("");
        this.lblSmartPlugStatus.setText(this.objSmartPlug_Grayhats.offSmartPlug());

    }//GEN-LAST:event_btnSmartPlugOffActionPerformed

    private void btnSmartPlugResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartPlugResetActionPerformed
        // TODO add your handling code here:

        this.lblSmartPlugStatus.setText("");
        this.lblSmartPlugStatus.setText(this.objSmartPlug_Grayhats.resetSmartPlug());

    }//GEN-LAST:event_btnSmartPlugResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartPlugTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartPlugTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartPlugTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartPlugTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartPlugTest().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSmartPlugOff;
    private javax.swing.JButton btnSmartPlugOn;
    private javax.swing.JButton btnSmartPlugReset;
    private javax.swing.JButton btnSmartPlugStatus;
    private javax.swing.JLabel lblSmartPlugStatus;
    private javax.swing.JLabel lblSmartPlugVersion;
    // End of variables declaration//GEN-END:variables
}
